const influencersData = [
  {
    id: 1,
    name: "Akash Singh",
    username: "travelbug_akash",
    category: "Travel",
    profilePic: "https://randomuser.me/api/portraits/men/32.jpg",
    stats: {
      instagram: "450.0K",
      facebook: "210.0K",
      twitter: "95.0K",
      youtube: "350.0K",
    },
    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    posts: [
      {
        image: "https://via.placeholder.com/300x200/ff4444/ffffff?text=Car",
        instagram: "200K",
        facebook: "500K",
        twitter: "500",
        youtube: "10K",
      },
      {
        image:
          "https://via.placeholder.com/300x200/4285F4/ffffff?text=Product+Review",
        instagram: "180K",
        facebook: "450K",
        twitter: "720",
        youtube: "9K",
      },
      {
        image:
          "https://via.placeholder.com/300x200/00C851/ffffff?text=Travel+Vlog",
        instagram: "220K",
        facebook: "600K",
        twitter: "950",
        youtube: "12K",
      },
    ],
  },
  {
    id: 2,
    name: "Anjali Rao",
    username: "foodieanjali",
    category: "Food",
    profilePic: "https://randomuser.me/api/portraits/women/44.jpg",
    stats: {
      instagram: "320.0K",
      facebook: "150.0K",
      twitter: "45.0K",
      youtube: "200.0K",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },

    posts: [],
  },
  {
    id: 3,
    name: "Neha Mehta",
    username: "fitnessneha",
    category: "Fitness",
    profilePic: "https://randomuser.me/api/portraits/women/68.jpg",
    stats: {
      instagram: "380.0K",
      facebook: "120.0K",
      twitter: "65.0K",
      youtube: "280.0K",
    },
    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    posts: [],
  },
  {
    id: 4,
    name: "Priya Sharma",
    username: "priyasharma",
    category: "Fashion",
    profilePic: "https://randomuser.me/api/portraits/women/12.jpg",
    stats: {
      instagram: "250.0K",
      facebook: "100.0K",
      twitter: "75.0K",
      youtube: "150.0K",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },

    posts: [],
  },
  {
    id: 5,
    name: "Rahul Kumar",
    username: "techrahul",
    category: "Technology",
    profilePic: "https://randomuser.me/api/portraits/men/91.jpg",
    stats: {
      instagram: "180.0K",
      facebook: "90.0K",
      twitter: "32.0K",
      youtube: "500.0K",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },

    posts: [],
  },
  {
    id: 3,
    name: "Neha Mehta",
    username: "fitnessneha",
    category: "Fitness",
    profilePic: "https://randomuser.me/api/portraits/women/68.jpg",
    stats: {
      instagram: "380.0K",
      facebook: "120.0K",
      twitter: "65.0K",
      youtube: "280.0K",
    },
    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    posts: [],
  },
  {
    id: 4,
    name: "Priya Sharma",
    username: "priyasharma",
    category: "Fashion",
    profilePic: "https://randomuser.me/api/portraits/women/12.jpg",
    stats: {
      instagram: "250.0K",
      facebook: "100.0K",
      twitter: "75.0K",
      youtube: "150.0K",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },

    posts: [],
  },
  {
    id: 5,
    name: "Rahul Kumar",
    username: "techrahul",
    category: "Technology",
    profilePic: "https://randomuser.me/api/portraits/men/91.jpg",
    stats: {
      instagram: "180.0K",
      facebook: "90.0K",
      twitter: "32.0K",
      youtube: "500.0K",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },

    posts: [],
  },
  {
    id: 3,
    name: "Neha Mehta",
    username: "fitnessneha",
    category: "Fitness",
    profilePic: "https://randomuser.me/api/portraits/women/68.jpg",
    stats: {
      instagram: "380.0K",
      facebook: "120.0K",
      twitter: "65.0K",
      youtube: "280.0K",
    },
    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    posts: [],
  },
  {
    id: 4,
    name: "Priya Sharma",
    username: "priyasharma",
    category: "Fashion",
    profilePic: "https://randomuser.me/api/portraits/women/12.jpg",
    stats: {
      instagram: "250.0K",
      facebook: "100.0K",
      twitter: "75.0K",
      youtube: "150.0K",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },

    posts: [],
  },
  {
    id: 5,
    name: "Rahul Kumar",
    username: "techrahul",
    category: "Technology",
    profilePic: "https://randomuser.me/api/portraits/men/91.jpg",
    stats: {
      instagram: "180.0K",
      facebook: "90.0K",
      twitter: "32.0K",
      youtube: "500.0K",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },

    posts: [],
  },
  {
    id: 1,
    name: "Akash Singh",
    username: "travelbug_akash",
    category: "Travel",
    profilePic: "https://randomuser.me/api/portraits/men/32.jpg",
    stats: {
      instagram: "450.0K",
      facebook: "210.0K",
      twitter: "95.0K",
      youtube: "350.0K",
    },
    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    posts: [
      {
        image: "https://via.placeholder.com/300x200/ff4444/ffffff?text=Car",
        instagram: "200K",
        facebook: "500K",
        twitter: "500",
        youtube: "10K",
      },
      {
        image:
          "https://via.placeholder.com/300x200/4285F4/ffffff?text=Product+Review",
        instagram: "180K",
        facebook: "450K",
        twitter: "720",
        youtube: "9K",
      },
      {
        image:
          "https://via.placeholder.com/300x200/00C851/ffffff?text=Travel+Vlog",
        instagram: "220K",
        facebook: "600K",
        twitter: "950",
        youtube: "12K",
      },
    ],
  },
  {
    id: 2,
    name: "Anjali Rao",
    username: "foodieanjali",
    category: "Food",
    profilePic: "https://randomuser.me/api/portraits/women/44.jpg",
    stats: {
      instagram: "320.0K",
      facebook: "150.0K",
      twitter: "45.0K",
      youtube: "200.0K",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },

    posts: [],
  },
  {
    id: 3,
    name: "Neha Mehta",
    username: "fitnessneha",
    category: "Fitness",
    profilePic: "https://randomuser.me/api/portraits/women/68.jpg",
    stats: {
      instagram: "380.0K",
      facebook: "120.0K",
      twitter: "65.0K",
      youtube: "280.0K",
    },
    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    posts: [],
  },
  {
    id: 4,
    name: "Priya Sharma",
    username: "priyasharma",
    category: "Fashion",
    profilePic: "https://randomuser.me/api/portraits/women/12.jpg",
    stats: {
      instagram: "250.0K",
      facebook: "100.0K",
      twitter: "75.0K",
      youtube: "150.0K",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },

    posts: [],
  },
  {
    id: 5,
    name: "Rahul Kumar",
    username: "techrahul",
    category: "Technology",
    profilePic: "https://randomuser.me/api/portraits/men/91.jpg",
    stats: {
      instagram: "180.0K",
      facebook: "90.0K",
      twitter: "32.0K",
      youtube: "500.0K",
    },
    data: {
      totalCampaigns: 90,
      avgLikes: 90,
      avgViews: "90K",
      avgReach: "500K",
      engagement: "90%",
      avgComments: 90,
      avgShares: 90,
      fakeFollowers: "1%",
    },

    prices: {
      "Post Image/Video": "499₹",
      "Reels/Shorts": "499₹",
      "Story (Image/Video)": "499₹",
      "Short Video (<10m)": "499₹",
      "Video (>10m)": "499₹",
      Polls: "499₹",
    },

    posts: [],
  },
];
export default influencersData;
