const services = [
  {
    id: 1,
    title: 'Product Review',
    platform: 'YouTube',
    image: 'https://picsum.photos/300/180?random=1',
    likes: '180K',
    views: '450K',
    comments: '720',
    shares: '9K',
  },
  {
    id: 2,
    title: 'Travel Vlog',
    platform: 'Twitter',
    image: 'https://picsum.photos/300/180?random=2',
    likes: '220K',
    views: '600K',
    comments: '950',
    shares: '12K',
  },
  {
    id: 3,
    title: 'Fitness Challenge',
    platform: 'Instagram',
    image: 'http://picsum.photos/300/180?random=3',
    likes: '195K',
    views: '520K',
    comments: '830',
    shares: '9K',
  },
  {
    id: 4,
    title: 'Cooking Tips',
    platform: 'Facebook',
    image: 'https://picsum.photos/300/180?random=4',
    likes: '150K',
    views: '430K',
    comments: '600',
    shares: '8K',
  },
  {
    id: 5,
    title: 'Unboxing',
    platform: 'YouTube',
    image: 'https://picsum.photos/300/180?random=5',
    likes: '200K',
    views: '550K',
    comments: '800',
    shares: '11K',
  },
  {
    id: 6,
    title: 'Beauty Tips',
    platform: 'Instagram',
    image: 'https://picsum.photos/300/180?random=6',
    likes: '175K',
    views: '490K',
    comments: '700',
    shares: '10K',
  },
  {
    id: 7,
    title: 'Tech Review',
    platform: 'Twitter',
    image: 'https://picsum.photos/300/180?random=7',
    likes: '230K',
    views: '620K',
    comments: '950',
    shares: '13K',
  },
  {
    id: 8,
    title: 'DIY Craft',
    platform: 'Facebook',
    image: 'https://picsum.photos/300/180?random=8',
    likes: '160K',
    views: '460K',
    comments: '670',
    shares: '9K',
  },
  {
    id: 9,
    title: 'Photography Tricks',
    platform: 'Instagram',
    image: 'https://picsum.photos/300/180?random=9',
    likes: '185K',
    views: '500K',
    comments: '790',
    shares: '10K',
  },
  {
    id: 10,
    title: 'Motivational Talk',
    platform: 'YouTube',
    image: 'https://picsum.photos/300/180?random=10',
    likes: '210K',
    views: '570K',
    comments: '870',
    shares: '12K',
  },
  {
    id: 11,
    title: 'Comedy Skit',
    platform: 'Facebook',
    image: 'https://picsum.photos/300/180?random=11',
    likes: '240K',
    views: '680K',
    comments: '1100',
    shares: '15K',
  },
  {
    id: 12,
    title: 'Pet Video',
    platform: 'Twitter',
    image: 'https://picsum.photos/300/180?random=12',
    likes: '190K',
    views: '510K',
    comments: '720',
    shares: '8K',
  },
  {
    id: 13,
    title: 'Dance Performance',
    platform: 'Instagram',
    image: 'https://picsum.photos/300/180?random=13',
    likes: '200K',
    views: '560K',
    comments: '840',
    shares: '10K',
  },
  {
    id: 14,
    title: 'Educational Tips',
    platform: 'YouTube',
    image: 'https://picsum.photos/300/180?random=14',
    likes: '170K',
    views: '480K',
    comments: '690',
    shares: '9K',
  },
  {
    id: 15,
    title: 'Fashion Haul',
    platform: 'Instagram',
    image: 'https://picsum.photos/300/180?random=15',
    likes: '215K',
    views: '590K',
    comments: '890',
    shares: '11K',
  },
  {
    id: 16,
    title: 'Book Review',
    platform: 'Twitter',
    image: 'https://picsum.photos/300/180?random=16',
    likes: '160K',
    views: '440K',
    comments: '620',
    shares: '7K',
  },
  {
    id: 17,
    title: 'Home Tour',
    platform: 'YouTube',
    image: 'https://picsum.photos/300/180?random=17',
    likes: '225K',
    views: '600K',
    comments: '930',
    shares: '12K',
  },
  {
    id: 18,
    title: 'Live Q&A',
    platform: 'Facebook',
    image: 'https://picsum.photos/300/180?random=18',
    likes: '180K',
    views: '470K',
    comments: '750',
    shares: '9K',
  },
  {
    id: 19,
    title: 'Gaming Stream',
    platform: 'Twitch',
    image: 'https://picsum.photos/300/180?random=19',
    likes: '250K',
    views: '700K',
    comments: '1200',
    shares: '16K',
  },
  {
    id: 20,
    title: 'Quick Recipes',
    platform: 'Instagram',
    image: 'https://picsum.photos/300/180?random=20',
    likes: '195K',
    views: '520K',
    comments: '810',
    shares: '10K',
  },
];

export default services;
